In [1]:
import pandas as pd
import numpy as np
import re
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import SimpleRNN,Dense,Embedding,LSTM
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences
import random
import tensorflow as tf
import numpy as np

In [29]:
corpus=[
    'wish you a very happy birthday',
    'python is widely used in AI and Automation',
    'virat kohli is a cricketer',
    'india is a great country',
    'noida is a city in india',
    'rajnikant is the superstar of south',
    'Virat kohli was the captain of ODI indian cricket team',
    'happy birthday to you'
]
corpus = [
    "मौसम आज बहुत अच्छा है",
    "मुझे चाय पीना पसंद है",
    "वह स्कूल जा रहा है",
    "सूरज पूर्व दिशा से उगता है",
    "रवि रोज सुबह दौड़ने जाता है",
    "मां ने स्वादिष्ट खाना बनाया",
    "मैं किताब पढ़ रहा हूँ",
    "हम कल बाजार जाएंगे",
    "भारत एक महान देश है",
    "बच्चे पार्क में खेल रहे हैं"
]
tk=Tokenizer()
tk.fit_on_texts(corpus)
print(tk.index_word)

{1: 'है', 2: 'रहा', 3: 'मौसम', 4: 'आज', 5: 'बहुत', 6: 'अच्छा', 7: 'मुझे', 8: 'चाय', 9: 'पीना', 10: 'पसंद', 11: 'वह', 12: 'स्कूल', 13: 'जा', 14: 'सूरज', 15: 'पूर्व', 16: 'दिशा', 17: 'से', 18: 'उगता', 19: 'रवि', 20: 'रोज', 21: 'सुबह', 22: 'दौड़ने', 23: 'जाता', 24: 'मां', 25: 'ने', 26: 'स्वादिष्ट', 27: 'खाना', 28: 'बनाया', 29: 'मैं', 30: 'किताब', 31: 'पढ़', 32: 'हूँ', 33: 'हम', 34: 'कल', 35: 'बाजार', 36: 'जाएंगे', 37: 'भारत', 38: 'एक', 39: 'महान', 40: 'देश', 41: 'बच्चे', 42: 'पार्क', 43: 'में', 44: 'खेल', 45: 'रहे', 46: 'हैं'}


In [30]:
sequences=tk.texts_to_sequences(corpus)
print(sequences)

[[3, 4, 5, 6, 1], [7, 8, 9, 10, 1], [11, 12, 13, 2, 1], [14, 15, 16, 17, 18, 1], [19, 20, 21, 22, 23, 1], [24, 25, 26, 27, 28], [29, 30, 31, 2, 32], [33, 34, 35, 36], [37, 38, 39, 40, 1], [41, 42, 43, 44, 45, 46]]


In [31]:
input_sequesces=[]
maxlen=0
for s in sequences:
    length=len(s)
    if length>maxlen:
        maxlen=length
    for i in range(1,len(s)):
        input_sequesces.append(s[:i+1])
print(maxlen)
input_sequesces

6


[[3, 4],
 [3, 4, 5],
 [3, 4, 5, 6],
 [3, 4, 5, 6, 1],
 [7, 8],
 [7, 8, 9],
 [7, 8, 9, 10],
 [7, 8, 9, 10, 1],
 [11, 12],
 [11, 12, 13],
 [11, 12, 13, 2],
 [11, 12, 13, 2, 1],
 [14, 15],
 [14, 15, 16],
 [14, 15, 16, 17],
 [14, 15, 16, 17, 18],
 [14, 15, 16, 17, 18, 1],
 [19, 20],
 [19, 20, 21],
 [19, 20, 21, 22],
 [19, 20, 21, 22, 23],
 [19, 20, 21, 22, 23, 1],
 [24, 25],
 [24, 25, 26],
 [24, 25, 26, 27],
 [24, 25, 26, 27, 28],
 [29, 30],
 [29, 30, 31],
 [29, 30, 31, 2],
 [29, 30, 31, 2, 32],
 [33, 34],
 [33, 34, 35],
 [33, 34, 35, 36],
 [37, 38],
 [37, 38, 39],
 [37, 38, 39, 40],
 [37, 38, 39, 40, 1],
 [41, 42],
 [41, 42, 43],
 [41, 42, 43, 44],
 [41, 42, 43, 44, 45],
 [41, 42, 43, 44, 45, 46]]

In [32]:
pad_input_sequences=pad_sequences(input_sequesces,maxlen=maxlen,padding='pre')
pad_input_sequences

array([[ 0,  0,  0,  0,  3,  4],
       [ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  3,  4,  5,  6],
       [ 0,  3,  4,  5,  6,  1],
       [ 0,  0,  0,  0,  7,  8],
       [ 0,  0,  0,  7,  8,  9],
       [ 0,  0,  7,  8,  9, 10],
       [ 0,  7,  8,  9, 10,  1],
       [ 0,  0,  0,  0, 11, 12],
       [ 0,  0,  0, 11, 12, 13],
       [ 0,  0, 11, 12, 13,  2],
       [ 0, 11, 12, 13,  2,  1],
       [ 0,  0,  0,  0, 14, 15],
       [ 0,  0,  0, 14, 15, 16],
       [ 0,  0, 14, 15, 16, 17],
       [ 0, 14, 15, 16, 17, 18],
       [14, 15, 16, 17, 18,  1],
       [ 0,  0,  0,  0, 19, 20],
       [ 0,  0,  0, 19, 20, 21],
       [ 0,  0, 19, 20, 21, 22],
       [ 0, 19, 20, 21, 22, 23],
       [19, 20, 21, 22, 23,  1],
       [ 0,  0,  0,  0, 24, 25],
       [ 0,  0,  0, 24, 25, 26],
       [ 0,  0, 24, 25, 26, 27],
       [ 0, 24, 25, 26, 27, 28],
       [ 0,  0,  0,  0, 29, 30],
       [ 0,  0,  0, 29, 30, 31],
       [ 0,  0, 29, 30, 31,  2],
       [ 0, 29, 30, 31,  2, 32],
       [ 0

In [33]:
X=pad_input_sequences[:,:-1]
y=pad_input_sequences[:,-1]

In [34]:
random.seed(42)
tf.random.set_seed(42)
np.random.seed(42)

model=Sequential()
model.add(Embedding(input_dim=len(tk.index_word)+1,output_dim=50))
model.add(SimpleRNN(units=200))
model.add(Dense(units=100,activation='relu'))
model.add(Dense(units=50,activation='relu'))
model.add(Dense(units=len(tk.index_word)+1,activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X,y,batch_size=10,epochs=50)

Epoch 1/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.0000e+00 - loss: 3.8539
Epoch 2/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1429 - loss: 3.8018 
Epoch 3/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1905 - loss: 3.7511 
Epoch 4/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2381 - loss: 3.6753
Epoch 5/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1667 - loss: 3.5799 
Epoch 6/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1667 - loss: 3.4793 
Epoch 7/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1667 - loss: 3.3535 
Epoch 8/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1667 - loss: 3.1869
Epoch 9/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1905 - loss: 3.0246 
Epoch 10/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1905 - loss: 2.8715 
Epoch 11/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2381 - loss: 2.7076
Epoch 12/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.2857 - loss: 2.54

In [36]:
text='मां'
seq=tk.texts_to_sequences([text])
print(seq)
pad_seq=pad_sequences(seq,maxlen=maxlen,padding='pre')
print(pad_seq)

index=np.argmax(model.predict(pad_seq))
print(tk.index_word[index])

[[24]]
[[ 0  0  0  0  0 24]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
ने


In [37]:
text='मौसम'
for i in range(4):
    print(text)
    seq=tk.texts_to_sequences([text])
    print(seq)
    pad_seq=pad_sequences(seq,maxlen=maxlen,padding='pre')
    print(pad_seq)
    
    index=np.argmax(model.predict(pad_seq))
    nextword=tk.index_word[index]
    print(nextword)
    text=text+' '+nextword

मौसम
[[3]]
[[0 0 0 0 0 3]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
आज
मौसम आज
[[3, 4]]
[[0 0 0 0 3 4]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
बहुत
मौसम आज बहुत
[[3, 4, 5]]
[[0 0 0 3 4 5]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
अच्छा
मौसम आज बहुत अच्छा
[[3, 4, 5, 6]]
[[0 0 3 4 5 6]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
है


In [38]:
corpus=[
    'wish you a very happy birthday',
    'python is widely used in AI and Automation',
    'virat kohli is a cricketer',
    'india is a great country',
    'noida is a city in india',
    'rajnikant is the superstar of south',
    'Virat kohli was the captain of ODI indian cricket team',
    'happy birthday to you',
    "मौसम आज बहुत अच्छा है",
    "मुझे चाय पीना पसंद है",
    "वह स्कूल जा रहा है",
    "सूरज पूर्व दिशा से उगता है",
    "रवि रोज सुबह दौड़ने जाता है",
    "मां ने स्वादिष्ट खाना बनाया",
    "मैं किताब पढ़ रहा हूँ",
    "हम कल बाजार जाएंगे",
    "भारत एक महान देश है",
    "बच्चे पार्क में खेल रहे हैं"
]
tk=Tokenizer()
tk.fit_on_texts(corpus)
sequences=tk.texts_to_sequences(corpus)
input_sequesces=[]
maxlen=0
for s in sequences:
    length=len(s)
    if length>maxlen:
        maxlen=length
    for i in range(1,len(s)):
        input_sequesces.append(s[:i+1])
pad_input_sequences=pad_sequences(input_sequesces,maxlen=maxlen,padding='pre')
X=pad_input_sequences[:,:-1]
y=pad_input_sequences[:,-1]

random.seed(42)
tf.random.set_seed(42)
np.random.seed(42)

model=Sequential()
model.add(Embedding(input_dim=len(tk.index_word)+1,output_dim=50))
model.add(SimpleRNN(units=200))
model.add(Dense(units=100,activation='relu'))
model.add(Dense(units=50,activation='relu'))
model.add(Dense(units=len(tk.index_word)+1,activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X,y,batch_size=10,epochs=50)

Epoch 1/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.0238 - loss: 4.4009    
Epoch 2/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0714 - loss: 4.3492     
Epoch 3/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0833 - loss: 4.2825 
Epoch 4/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0952 - loss: 4.2141 
Epoch 5/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0952 - loss: 4.1091 
Epoch 6/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1071 - loss: 3.9837 
Epoch 7/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1310 - loss: 3.8442 
Epoch 8/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1429 - loss: 3.6556
Epoch 9/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1667 - loss: 3.4668 
Epoch 10/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2143 - loss: 3.2677 
Epoch 11/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2500 - loss: 3.0802 
Epoch 12/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3452 - loss: 2.

In [40]:
text='virat'
seq=tk.texts_to_sequences([text])
print(seq)
pad_seq=pad_sequences(seq,maxlen=maxlen,padding='pre')
print(pad_seq)

index=np.argmax(model.predict(pad_seq))
print(tk.index_word[index])

[[8]]
[[0 0 0 0 0 0 0 0 0 8]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
kohli


In [41]:
from gensim.models import Word2Vec

In [42]:
sentences = [
 ['food', 'was', 'good'],
 ['taste', 'was', 'not', 'good'],
 ['will', 'not', 'recommend', 'to', 'others'],
 ['service', 'was', 'very', 'prompt'],
 ['awesome', 'food'],
]

In [45]:
emb_model=Word2Vec(
    sentences=sentences,
    vector_size=5,
    sg=1,               # 1=Skip-Gram, 0=CBOW
    window=2,
    min_count=1          # ignore words with frequency < 1
)

In [54]:
word='sonu'
if word in emb_model.wv.key_to_index:
    print(emb_model.wv.get_vector(word))
else:
    print(word,'not found')
    print(np.zeros(5)) 

sonu not found
[0. 0. 0. 0. 0.]


In [55]:
from gensim.models import KeyedVectors
emd_model=KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin.gz',binary=True)

In [61]:
emd_model.get_vector('food')

array([-0.18164062,  0.16503906, -0.16601562,  0.35742188, -0.09228516,
        0.20117188, -0.0546875 , -0.26171875, -0.17285156, -0.08056641,
        0.14648438, -0.24609375,  0.18652344,  0.10253906, -0.3203125 ,
        0.16699219, -0.0032196 , -0.06640625,  0.06591797, -0.109375  ,
        0.13964844, -0.05029297,  0.25390625,  0.0859375 ,  0.02026367,
        0.05517578, -0.08447266,  0.07324219,  0.15429688, -0.13867188,
       -0.25195312, -0.15136719,  0.07958984,  0.00848389, -0.24902344,
        0.05224609,  0.04394531, -0.19726562, -0.2109375 ,  0.01477051,
       -0.23632812, -0.14355469,  0.17773438,  0.26757812, -0.08789062,
       -0.07910156, -0.16113281,  0.23632812, -0.07177734,  0.08837891,
        0.07177734, -0.11962891, -0.09228516, -0.12060547, -0.00448608,
       -0.21875   , -0.05712891, -0.04418945,  0.07226562, -0.05883789,
       -0.12597656,  0.03125   , -0.24609375,  0.19140625,  0.14941406,
       -0.19335938, -0.1875    , -0.05126953,  0.03369141, -0.21

In [64]:
emd_model.most_similar('chair',topn=3)

[('chairs', 0.7871319055557251),
 ('Chair', 0.748843789100647),
 ('chairperson', 0.6301862597465515)]

In [65]:
emd_model.most_similar(positive=['king','female'],negative=['male'],topn=1)

[('queen', 0.6660672426223755)]